### ISSUE TITLE
You can’t attach an IP-based policy to a domain that has a VPC endpoint.

### ISSUE THREAD

**Issue by Tomthi** [clouddrove/terraform-aws-elasticsearch#11]
I'm not sure why I'm getting this error. I'm attaching a security group. Where do I disable the IP-based policy?

Error: InvalidTypeException: You can’t attach an IP-based policy to a domain that has a VPC endpoint. Instead, use a security group to control IP-based access.
│
│   with module.elasticsearch.aws_elasticsearch_domain_policy.default[0],
│   on .terraform/modules/elasticsearch/main.tf line 464, in resource "aws_elasticsearch_domain_policy" "default":
│  464: resource "aws_elasticsearch_domain_policy" "default" {
│

**Comment by sohanyadav** [comment]
@Tomthi  we will check and get back to you ASAP

**Comment by sohanyadav** [comment]
@Tomthi  if you deploy the elasticsearch with VPC, you need to enable   `vpc_enabled        = [true`](https://github.com/clouddrove/terraform-aws-elasticsearch/blob/master/_example/single_node_vpc/example.tf#L61)

now we created a separate [example]( https://github.com/clouddrove/terraform-aws-elasticsearch/blob/master/_example/single_node_vpc/example.t
) for VPC,  it will be easy to understand
