### ISSUE TITLE
Cant override or remove default tags (managedby, repository)

### ISSUE THREAD

**Issue by aswath-pt** [clouddrove/terraform-aws-elasticsearch#16]

**Comment by theprashantyadav** [comment]
Hi @aswath-pt if you need to change both variables (managedby, repository) you can change in main.tf file 
https://github.com/clouddrove/terraform-aws-elasticsearch/blob/master/main.tf#L17
https://github.com/clouddrove/terraform-aws-elasticsearch/blob/master/main.tf#LL15C1-L15C1
